apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - staging-routing.yaml

namePrefix: staging-

configMapGenerator:
  - name: global-env-metadata
    literals:
      - ENVIRONMENT=staging
      - LOG_LEVEL=debug

patches:
  - path: patch-compute-staging.yaml
  - path: patch-apps-staging.yaml
