apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-async-worker
  namespace: billing-domain
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
