apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - global-configmap.yaml
  - external-secret-template.yaml
  - order-service-base.yaml
  - order-service-db.yaml
  - order-service-migration.yaml
  - billing-service-base.yaml
  - billing-service-redis.yaml
  - billing-service-worker.yaml
  - catalog-service-base.yaml
  - telemetry-service-base.yaml
  - auth-service-base.yaml

helmCharts:
  - name: nginx
    repo: https://bitnami.com
    version: 18.2.3
    releaseName: core-web
    valuesFile: helm-values.yaml
    includeCRDs: true

