apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - dev-routing.yaml

namePrefix: dev-

configMapGenerator:
  - name: global-env-metadata
    literals:
      - ENVIRONMENT=development
      - LOG_LEVEL=trace

patches:
  - path: patch-compute-dev.yaml
  - path: patch-apps-dev.yaml
