apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monorepo-services-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com'
    targetRevision: HEAD
    path: enterprise-devops/application/overlays/staging
  destination:
    server: 'https://default.svc'
    namespace: infra-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
