apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.io'
    chart: cloudnative-pg
    targetRevision: 0.21.0 # Production-locked stable chart version
    helm:
      releaseName: cloudnative-pg
  destination:
    server: 'https://default.svc'
    namespace: data-tier
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
