apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.io'
    chart: external-dns
    targetRevision: 1.14.3
    helm:
      releaseName: external-dns
      valuesInline:
        provider: aws
        env:
          - name: AWS_REGION
            value: us-east-1
        domainFilters:
          - yourcompany.com
        policy: sync
  destination:
    server: 'https://default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
