apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-community-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.io'
    chart: mongodb-operator
    targetRevision: 1.4.3
    helm:
      releaseName: mongodb-operator
  destination:
    server: 'https://default.svc'
    namespace: data-tier
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
