apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prod-microservice-read-only-role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-processor-sa
  namespace: orders-domain
  automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod-order-processor-rbac-bind
  namespace: orders-domain
subjects:
  - kind: ServiceAccount
    name: order-processor-sa
    namespace: orders-domain
roleRef:
  kind: ClusterRole
  name: prod-microservice-read-only-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: billing-worker-sa
  namespace: billing-domain
  automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod-billing-worker-rbac-bind
  namespace: billing-domain
subjects:
  - kind: ServiceAccount
    name: billing-worker-sa
    namespace: billing-domain
roleRef:
  kind: ClusterRole
  name: prod-microservice-read-only-role
  apiGroup: rbac.authorization.k8s.io
