apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prod-database-credentials
  namespace: infra-production
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager-backend
    kind: ClusterSecretStore
  target:
    name: prod-core-app-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      engineVersion: v2
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: production/database/credentials
        property: connection_string
