apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - app-rbac-policies.yaml
  - prod-routing.yaml
  - external-secret.yaml

namePrefix: prod-

configMapGenerator:
  - name: global-env-metadata
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=warn

patches:
  - target:
      kind: Deployment
      name: billing-async-worker
      namespace: billing-domain
    path: canary-rollout.yaml
  - target:
      kind: Deployment
      name: order-processor-engine
      namespace: orders-domain
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
  - target:
      kind: Deployment
      name: stateless-token-auth
      namespace: security-auth-domain
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
