apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - app-rbac-policies.yaml
  - prod-routing.yaml
  - external-secret.yaml
  - canary-rollouts/order-canary.yaml
  - canary-rollouts/billing-canary.yaml
  - canary-rollouts/catalog-canary.yaml
  - canary-rollouts/telemetry-canary.yaml
  - canary-rollouts/auth-canary.yaml

namePrefix: prod-

configMapGenerator:
  - name: global-env-metadata
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=warn
